spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rest_api_test
    username: rest_api_test
    password: rest_api_test
  jpa:
    hibernate:
      ddl-auto: update
